pipeline:
  build:
    image: maven
    environment:
      - MAVEN_REPO_KEY=libs-snapshot 
    secrets: [ ARTIFACTORY_URL, ARTIFACTORY_USER,ARTIFACTORY_PASS ]
    commands:
      - curl -fL https://getcli.jfrog.io | sh
      - echo $ARTIFACTORY_USER
      - echo $ARTIFACTORY_PASSWORD    
      - ./jfrog rt config --url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASS
      - ./jfrog rt c show
      - export M2_HOME=/usr/share/maven
      - sed -i 's,MAVEN_REPO_KEY,'"$MAVEN_REPO_KEY"',g' configuration.yml
      - ./jfrog rt mvn "clean install" configuration.yml --build-name=batel_drone --build-number=1.0.0
      - ./jfrog rt bce batel_drone 1.0.0
      - ./jfrog rt bp batel_drone 1.0.0
