pipeline:
  build:
    image: maven
    secrets: [ artifactory_password, ARTIFACTORY_USER, ARTIFACTORY_URL, maven_repo_key ]
    commands:
      - curl -fL https://getcli.jfrog.io | sh
      - ./jfrog rt config --url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --password=$ARTIFACTORY_PASSWORD
      - ./jfrog rt c show
      - export M2_HOME=/usr/share/maven
      - sed -i 's,MAVEN_REPO_KEY,'"$MAVEN_REPO_KEY"',g' configuration.yml
      - ./jfrog rt mvn "clean install" configuration.yml --build-name=batel_drone --build-number=1.0.0
      - ./jfrog rt bce batel_drone 1.0.0
      - ./jfrog rt bp batel_drone 1.0.0
